a=int(input('Please tell me a year.\n'))
if(a%400==0):print('It\'s a leap year!')
elif(a%100==0):print('It\'s an average year!')
elif(a%4==0):print('It\'s a leap year!')
else:print('It\'s an average year!')
